version: "3.8"
services:
  web:
    build: ../web
    ports:
      - "8000:8000"
    environment:
      WORKER_URL: http://worker:9000/enqueue
    depends_on:
      - worker

  worker:
    build: ../worker
    ports:
      - "9000:9000"

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    ports:
      - "8001:8000"
    environment:
      CHROMA_API_IMPL: chroma
      CHROMA_SERVER_HOST: 0.0.0.0
